Referenced by issue #63594, python error in batch_for_shader when using more than one "in" parameter in a custom shader
