Referenced by pull request #125296, GPv3: Python error after `active_layer` renaming
Referenced by commit e373625e73d3dfbe68957fed5728f53c2fd942b5, GPv3: Python error after `active_layer` renaming
Referenced by commit ec220c17f52e4ca63dd0a6daa3af6f1dfda35146, GPv3: Rename `active_group` to `active`
