Referenced by pull request #125296, GPv3: Python error after `active_layer` renaming
