Referenced by commit 74dfb7ca23b, Fix T97731: Python traceback no longer includes line-numbers
