Referenced by issue #71983, script_pyapi_idprop_datablock test fails
